version: "3"
services:
  node_1:
    container_name: node_1_container
    environment:
      - GENESIS_TIMESTAMP=${GENESIS_TIMESTAMP}
      #- RUST_BACKTRACE=full (Debug)
    image: node_1_image
    user: ${OS_USER_NAME}
    command: "./massa-node -p ${NODE_WALLET_PWD}"
    # command: ["python3", "-m", "http.server"] # Debug
    ports: # HOST:CONTAINER
       - "33034:33034" # jsonrpc api private
       - "33035:33035" # jsonrpc api public
    networks:
      massa_cloud_network:
        ipv4_address: "11.0.0.11"
      
networks:
  massa_cloud_network:
    ipam:
      driver: default
      config:
        - subnet: "11.0.0.0/16"
        