version: "3.3"
services:
  poc-testnet-node-1:
    container_name: poc-testnet-1
    build:
      context: .
      dockerfile: ./Dockerfile
    image: massa/poc-testnet:v1
    user: "user"
    #restart: always
    ports:
      - "33034:33034"
    command: "python3 -m http.server 8000"
    #volumes:
    #  - VAR:path_value

  poc-testnet-node-2:
    container_name: poc-testnet-2
    build:
      context: .
      dockerfile: ./Dockerfile
    image: massa/poc-testnet:v1
    user: "user"
    command: "python3 -m http.server 8000"
    #restart: always
    ports:
      - "33034:43034"
    #volumes:
    #  - VAR:path_value
