version: "3.3"
services:
  poc-testnet-node-1:
    container_name: poc-testnet-1
    build:
      context: .
      dockerfile: ./Dockerfile
    image: massa/poc-testnet:v1
    env_file: .env
    user: ${user}
    #restart: always
    ports:
      - "33034:33034"
      #- "33034:53034"
      #- "33035:53035"
    command: "python3 -m http.server 8000"

  poc-testnet-node-2:
    container_name: poc-testnet-2
    build:
      context: .
      dockerfile: ./Dockerfile
    image: massa/poc-testnet:v1
    env_file: .env
    user: ${user}
    command: "python3 -m http.server 8000"
    #restart: always
    ports:
      - "33035:33035"
      #- "33034:43034"
      #- "33035:43035"
