version: "3.8"
services:
  node_1:
    container_name: node_1_container
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_USER: ${OS_USER_NAME}
        MASSA_GIT_REPO: ${MASSA_GIT_REPO}
        MASSA_GIT_BRANCH: ${MASSA_GIT_BRANCH}
        CARGO_BUILD_JOBS: ${CARGO_BUILD_JOBS}
        USER_PWD: ${OS_USER_PWD}
        BOOTSTRAP_IP: ""
        BOOTSTRAP_PUBK: ""
        NODE_IP: ${NODE_1_IP}
        NODE_PRIVKEY_FILE: config/node_1_privkey.key
        NODE_STAKING_FILE: config/node_1_staking_wallet.dat
        NODE_CONFIG_INITIAL_LEDGER: config/initial_ledger.json
        NODE_CONFIG_INITIAL_ROLLS: config/initial_rolls.json
        CONFIG_USER_TWEAK: ${CONFIG_USER_TWEAK}
    environment:
      - GENESIS_TIMESTAMP=${GENESIS_TIMESTAMP}
      #- RUST_BACKTRACE=full (Debug)
    image: node_1_image
    user: ${OS_USER_NAME}
    command: "./massa-node -p ${NODE_WALLET_PWD}"
    # command: ["python3", "-m", "http.server"] # Debug
    ports: # HOST:CONTAINER
       - "33034:33034" # jsonrpc api private
       - "33035:33035" # jsonrpc api public
    networks:
      massa_cloud_network:
        ipv4_address: "11.0.0.11"

  node_2:
    container_name: node_2_container
    build:  
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_USER: ${OS_USER_NAME}
        MASSA_GIT_REPO: ${MASSA_GIT_REPO}
        MASSA_GIT_BRANCH: ${MASSA_GIT_BRANCH}
        CARGO_BUILD_JOBS: ${CARGO_BUILD_JOBS}
        USER_PWD: ${OS_USER_PWD}
        BOOTSTRAP_IP: ${NODE_1_IP}
        BOOTSTRAP_PUBK: ${NODE_1_ID}
        NODE_IP: ${NODE_2_IP}
        NODE_PRIVKEY_FILE: config/node_2_privkey.key
        NODE_STAKING_FILE: config/node_2_staking_wallet.dat
        NODE_CONFIG_INITIAL_LEDGER: config/initial_ledger.json
        NODE_CONFIG_INITIAL_ROLLS: config/initial_rolls.json
        CONFIG_USER_TWEAK: ${CONFIG_USER_TWEAK}
    environment:
      - GENESIS_TIMESTAMP=${GENESIS_TIMESTAMP}
      #- RUST_BACKTRACE=full (Debug)
    image: node_2_image
    user: ${OS_USER_NAME}
    depends_on:
      - node_1
    command: ["python3", "./wait_ts.py", "./massa-node", "-p", "${NODE_WALLET_PWD}"]
    # command: ["python3", "-m", "http.server"] # Debug
    ports: # HOST:CONTAINER
      - "34034:33034" # jsonrpc private
      - "34035:33035" # jsonrpc public
      # - "34036:33036" # grpc
    networks:
      massa_cloud_network:
        ipv4_address: "11.0.0.12"

  node_3:
    container_name: node_3_container
    build:  
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_USER: ${OS_USER_NAME}
        MASSA_GIT_REPO: ${MASSA_GIT_REPO}
        MASSA_GIT_BRANCH: ${MASSA_GIT_BRANCH}
        CARGO_BUILD_JOBS: ${CARGO_BUILD_JOBS}
        USER_PWD: ${OS_USER_PWD}
        BOOTSTRAP_IP: ${NODE_1_IP}
        BOOTSTRAP_PUBK: ${NODE_1_ID}
        NODE_IP: ${NODE_3_IP}
        NODE_PRIVKEY_FILE: config/node_3_privkey.key
        NODE_STAKING_FILE: config/node_3_staking_wallet.dat
        NODE_CONFIG_INITIAL_LEDGER: config/initial_ledger.json
        NODE_CONFIG_INITIAL_ROLLS: config/initial_rolls.json
        CONFIG_USER_TWEAK: ${CONFIG_USER_TWEAK}
    environment:
      - GENESIS_TIMESTAMP=${GENESIS_TIMESTAMP}
      #- RUST_BACKTRACE=full (Debug)
    image: node_3_image
    user: ${OS_USER_NAME}
    depends_on:
      - node_1
    command: ["python3", "./wait_ts.py", "./massa-node", "-p", "${NODE_WALLET_PWD}"]
    # command: ["python3", "-m", "http.server"] # Debug
    ports: # HOST:CONTAINER
      - "35034:33034" # jsonrpc private
      - "35035:33035" # jsonrpc public
      # - "34036:33036" # grpc
    networks:
      massa_cloud_network:
        ipv4_address: "11.0.0.13"


  node_4:
    container_name: node_4_container
    build:  
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_USER: ${OS_USER_NAME}
        MASSA_GIT_REPO: ${MASSA_GIT_REPO}
        MASSA_GIT_BRANCH: ${MASSA_GIT_BRANCH}
        CARGO_BUILD_JOBS: ${CARGO_BUILD_JOBS}
        USER_PWD: ${OS_USER_PWD}
        BOOTSTRAP_IP: ${NODE_1_IP}
        BOOTSTRAP_PUBK: ${NODE_1_ID}
        NODE_IP: ${NODE_4_IP}
        NODE_PRIVKEY_FILE: config/node_4_privkey.key
        NODE_STAKING_FILE: config/node_4_staking_wallet.dat
        NODE_CONFIG_INITIAL_LEDGER: config/initial_ledger.json
        NODE_CONFIG_INITIAL_ROLLS: config/initial_rolls.json
        CONFIG_USER_TWEAK: ${CONFIG_USER_TWEAK}
    environment:
      - GENESIS_TIMESTAMP=${GENESIS_TIMESTAMP}
      #- RUST_BACKTRACE=full (Debug)
    image: node_4_image
    user: ${OS_USER_NAME}
    depends_on:
      - node_1
    command: ["python3", "./wait_ts.py", "./massa-node", "-p", "${NODE_WALLET_PWD}"]
    # command: ["python3", "-m", "http.server"] # Debug
    ports: # HOST:CONTAINER
      - "36034:33034" # jsonrpc private
      - "36035:33035" # jsonrpc public
      # - "34036:33036" # grpc
    networks:
      massa_cloud_network:
        ipv4_address: "11.0.0.14"



networks:
  massa_cloud_network:
    ipam:
      driver: default
      config:
        - subnet: "11.0.0.0/16"