version: "3.3"
services:
  poc-testnet-node-1:
    container_name: poc-testnet-1
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_USER: ${BUILD_USER}
        USER_PSWD: ${USER_PSWD}
        NODE_PSWD: ${NODE_PSWD}
        BOOTSTRAP_IP: ""
        BOOTSTRAP_PUBK: ""
        NODE_PRIVKEY_FILE: config/node_privkey.key
        INITIAL_LEDGER_FILE: config/initial_ledger.json
        INITIAL_ROLLS_FILE: config/initial_rolls.json

    image: massa_poc-testnet-1
    user: ${BUILD_USER}
    command: "./massa-node -p ${NODE_PSWD}"
    ports:
      - target: 33034 # Inside the container
        published: 33034 # Exposed Port
        protocol: tcp
        mode: host
      - target: 34035
        published: 33035
        protocol: tcp
        mode: host
    networks:
      massa_cloud_network:
        ipv4_address: 10.0.0.11

  poc-testnet-node-2:
    container_name: poc-testnet-2
    build:  
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_USER: ${BUILD_USER}
        USER_PSWD: ${USER_PSWD}
        NODE_PSWD: ${NODE_PSWD}
        BOOTSTRAP_IP: ${NODE_IP_1}
        BOOTSTRAP_PUBK: ${NODE_PUBK_1}
        NODE_PRIVKEY_FILE: config/node_privkey_2.key
        INITIAL_LEDGER_FILE: config/initial_ledger_2.json
        INITIAL_ROLLS_FILE: config/initial_rolls_2.json
    image: massa_poc-testnet-2
    user: ${BUILD_USER}
    command: "./massa-node -p ${NODE_PSWD}"
    ports:
      - target: 33035
        published: 34035
        protocol: tcp
        mode: host
      - target: 33034
        published: 34034
        protocol: tcp
        mode: host
    networks:
      massa_cloud_network:
        ipv4_address: 10.0.0.12


networks:
  massa_cloud_network:
    name: massa_cloud_network
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.254
