apiVersion: v1
kind: ConfigMap
metadata:
  name: nodes-config
  namespace: default
data:
  OS_USER_NAME: "user"
  OS_USER_PWD: "user"
  MASSA_GIT_REPO: "https://github.com/massalabs/massa.git"
  MASSA_GIT_BRANCH: "testnet_19"
  CARGO_BUILD_JOBS: "8"
  NODE_WALLET_PWD: "massa"
  NODE_1_IP: "11.0.0.11"
  NODE_1_SECRET_KEY: "S12g19LGdyS4n14iPnXUg1QdffbJZikWsLRWJa6grncz2k9dZa5M"
  NODE_1_PUBLIC_KEY: "P1Sy9Fm1iRNi6QdLNqDWrUyV4wFwMDzEgVZngLzPBK99fP9i5EQ"
  NODE_1_ID: "N1Sy9Fm1iRNi6QdLNqDWrUyV4wFwMDzEgVZngLzPBK99fP9i5EQ"
  NODE_1_ADDRESS: "A12BUit1MvW3ZnTtgYwAd4j8D4ZGA6BQo7GVnrMyByqmttiLeV5K"
  NODE_2_IP: "11.0.0.12"
  NODE_2_SECRET_KEY: "S138ChkJEUbq9MTKNrvt53LBSvmxDhQn9wKj7TL9CTj6QbedxJD"
  NODE_2_PUBLIC_KEY: "P1YyWXenTz9jthow4FzrrZXcNA5Rk1bvv2FBKG2gtEn2PainTWJ"
  NODE_2_ID: "N1YyWXenTz9jthow4FzrrZXcNA5Rk1bvv2FBKG2gtEn2PainTWJ"
  NODE_2_ADDRESS: "A1bATGfhM45J62UQySTV41iHvBFBtJa1j3ZqsUrDxmfhvs5XW95"
  NODE_1_API_URL_PRIVATE: "http://127.0.0.1:33034"
  NODE_1_API_URL_PUBLIC: "http://127.0.0.1:33035"
  NODE_2_API_URL_PRIVATE: "http://127.0.0.1:34034"
  NODE_2_API_URL_PUBLIC: "http://127.0.0.1:34035"
  GENESIS_TIMESTAMP: "1675451484000"