apiVersion: apps/v1
kind: Deployment
metadata:
  name: massa-node-3
 
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: node-3
  template:
    metadata:
      labels:
        app: node-3
    spec:
      containers:
        - name: node-3
          image: arshavee/massa-node:v14
          env:
          - name: GENESIS_TIMESTAMP
            value: "1685531640000"
          
          # ports:
          #   - containerPorapiVersion: apps/v1
          ports:
            - containerPort: 33034
            - containerPort: 33035
          volumeMounts:
            - name: config-volume-3
              mountPath: /massa/massa-node/config
              readOnly: true
            - name: base-initial-peers-3
              mountPath: /massa/massa-node/base_config/initial_peers.json
              subPath: "initial_peers.json"
              readOnly: true
            - name: base-initial-roles-3
              mountPath: /massa/massa-node/base_config/initial_rolls.json
              subPath: "initial_rolls.json"
              readOnly: true 
             #  for the debug_logs only  
            - name: base-config-3
              mountPath: /massa/massa-node/base_config/config.toml
              subPath: "config.toml"
              readOnly: true     
   
      volumes:
          - name: config-volume-3
            secret:
              secretName: massa-secrets-3
          - name: base-initial-peers-3
            configMap:
              name: base-config-initial-peers
          - name: base-initial-roles-3
            configMap:
              name: base-config-initial-rolls    
          
          #  for the debug_logs only
          - name: base-config-3
            configMap:
              name: base-config     
# kubectl create secret generic massa-secrets-3 \
#     --from-file=node_privkey.key=/home/arshavee/Desktop/MASSA\ internship/massa-cloud-simulator-main/config/node_keypair_3.key \
#     --from-file=staking_wallet.dat=/home/arshavee/Desktop/MASSA\ internship/massa-cloud-simulator-main/config/staking_wallet_3.dat


# kubectl create configmap massa-node-base-config \
#       --from-file=initial_peers.json=/home/arshavee/Desktop/MASSA\ internship/massa-cloud-simulator-main/base_config/initial_peers.json \
#       --from-file=initial_rolls.json=/home/arshavee/Desktop/MASSA\ internship/massa-cloud-simulator-main/config/initial_rolls.json


# to update configmap
# kubectl create configmap massa-node-base-config \
#   --from-file=initial_peers.json=/home/arshavee/Desktop/MASSA\ internship/massa-cloud-simulator-main/base_config/initial_peers.json \
#   --from-file=initial_rolls.json=/home/arshavee/Desktop/MASSA\ internship/massa-cloud-simulator-main/config/initial_rolls.json \

